// src/components/Header/Header.jsx
import "./Header.css";

function Header() {
  return (
    <div class="header-wrapper">
      <div className="header-content">
        <a className="header-item" href="#section1">
          Section 2
        </a>
        <a className="header-item" href="#section2">
          Section 2
        </a>
        <a className="header-item" href="#section3">
          Section 2
        </a>
        <a className="header-item" href="#section4">
          Section 2
        </a>
        <a className="header-item" href="#section5">
          Section 2
        </a>
        <a className="header-item" href="#section6">
          Section 2
        </a>
      </div>
    </div>
  );
}
export default Header;

// src/components/Header/Header.vue
<template>
    <div class="header-wrapper">
      <div className="header-content">
        <a className="header-item" href="#section1">
          Section 2
        </a>
        <a className="header-item" href="#section2">
          Section 2
        </a>
        <a className="header-item" href="#section3">
          Section 2
        </a>
        <a className="header-item" href="#section4">
          Section 2
        </a>
        <a className="header-item" href="#section5">
          Section 2
        </a>
        <a className="header-item" href="#section6">
          Section 2
        </a>
      </div>
    </div>
</template>

<style src="./Header.css" lang="css" scoped></style>
